services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sangxanh-be-container 
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: ${RESTART_POLICY:-unless-stopped}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge