name: Run command on remote server

on:

  push:

    branches:

      - main

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: SSH

        run: |

          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY_VALUE }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}

          mkdir hello-w
